---
title: " "
---




<br>
<br>
<br>


## Osnovne informacije

U kolegiju se obrađuju osnove statistike organizirane u tri cjeline:
1. deskriptivna statistika i vizualizacija
2. statistička teorija
3. inferencijalna statistika *(statistički modeli)*.

Primjenjeni aspekt kolegija odnosi na provedbu statističkih koncepata u [programskom jeziku R](https://www.r-project.org/). Pri tome je naglasak na osnovnoj `base::` sintaksi programskog jezika R, a manje na korištenju specifičnih paketa.  


Cilj kolegija je dvojak: 1) utvrđivanje osnovnih statističkih koncepata, 2) osposobljavanje za rad s podatcima i samostalnu provedbu statističke analize. Pri tome je veći naglasak stavljen na praktičnu primjenu statističkih koncepata nego na statističku teoriju. Kolegij ne zahtjeva prethodno poznavanje programskog jezika R no najveću će korist ostvariti studenti koji materijale (ili dio) prate u kroz jezik R. Studentima se preporuča instalacija [Git](https://git-scm.com/)-a i doprinos kolegiju kroz [GitHub](https://github.com/) (primjerice kroz ispravke grešaka ili poboljšanje materijala...). Materijali u ovom repozitoriju su napravljeni po [Open Source](https://opensource.org/) principima.


Kolegij će studentima društvenih znanosti omogućiti uključivanje u modernu paradigmu rada sa podatcima i otvoriti perspektivu rada sa [Data Science](https://www.edureka.co/blog/what-is-data-science/) i [Big Data](https://www.oracle.com/big-data/what-is-big-data.html) tehnologijama. Na taj način kolegij studentima otvara priliku [produbljenja akademskih vještina](https://www.thebritishacademy.ac.uk/documents/206/Society-Counts-Quantitative-Skills-in-the-Social-Sciences-Humanities-Position-_3xJi9mM.pdf) (*provedba kvantitativne empirijske analize*), povećava [mogućnosti zaposlenja](https://studyonline.unsw.edu.au/blog/data-science-degree-jobs) (*na strani analitike ili pojektnog IT menadzmenta*) i doprinosi smanjenju STEM jaza. 

<br>

## Literatura

Koristiti ćemo tri knjige.

<a href="https://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf">Learning statistics with R (LSR)</a>
<br><i>od Danielle Navarro.</i> 
<br>Ovo je glavna literatura. <a href = "https://learningstatisticswithr.com/">Pogledajte</a> i dodatne materijale koji prate knjigu. Dostupna je i <a href="https://learningstatisticswithr.com/book/">bookdown</a> verzija.


<a href="https://www.superknjizara.hr/?page=knjiga&id_knjiga=90301">Osnovne statističke metode za nematematičare</a>
<br><i>od Boris Petz.</i> 
<br>Ovo je također glavna literatura i preporuča se studentima koji ne polože ispit preko kolokvija.


<a href="http://daviddalpiaz.github.io/appliedstats/applied_statistics.pdf">Applied Statistics with R</a>
<br><i>od David Dalpiaz.</i> 
<br>Dodatna literatura za one koji žele znati više. Dostupna je i <a href="http://daviddalpiaz.github.io/appliedstats/">bookdown</a> verzija.

**Za one koji žele znati više postoji nekoliko (novih) izvrsnih udžbenika iz statistike u R:**

<a href="https://www.openintro.org/book/ims/">Introduction to Modern Statistics</a>
<br><i>od Mine Çetinkaya-Rundel i Johanna Hardin.</i> 
<br>Mmoderan i kvalitetan udžbenik iz statistike za jezik R. Dostupan je i u <a href="https://openintro-ims.netlify.app/">bookdown</a> verziji.


<a href="https://www.barnesandnoble.com/w/modern-statistics-with-r-m-ns-thulin/1139979246">Modern Statistics with R</a>
<br><i>od Måns Thulin.</i> 
<br>Sveobuhvatan udžbenik sa dodatnim i naprednijim temama. Dostupan je i u <a href="http://modernstatisticswithr.com/">bookdown</a> verziji.

<a href="https://www.routledge.com/Statistical-Inference-via-Data-Science-A-ModernDive-into-R-and-the-Tidyverse/Ismay-Kim/p/book/9780367409821">Statistical Inference via Data Science: A ModernDive into R and the Tidyverse</a>
<br><i>od Chester Ismay i Albert Y. Kim.</i> 
<br>Iznimno koristan udžbenik sa koji pristupa statistici iz perspektive podatkovnih znanosti. Dostupan je i u <a href="https://moderndive.com/index.html">bookdown</a> verziji.


<br>



## Polaganje ispita i kolokvija

U zimskom , ljetnom i jesenskom ispitnom roku studenti imaju završni pismeni ispit iz tema obrađenih na predavanjima i prema priloženoj literaturi. Ispit je položen ako student ostvari 60% od ukupno mogućih bodova: 60-64% = (2); 65-74% = (3); 75-84% = (4); 85% = (5).

<br>

## Prezentacija/seminarski rad

Svi studenti tijekom semestra moraju održati jednu prezentaciju prema zadanoj literaturi u .ppt formi. Izlagači moraju pripremiti na kraju prezentacije i nekoliko (2-3) ključnih pitanja za raspravu koju imamo na kraju obrađene teme. Prezentaciju studenti moraju poslati na e-mail najkasnije u petak, tjedan dana prije seminara. Seminari osim prezentacije uključuju: povezivanje teorijskih koncepata s praktičnom primjenom, zajednička empirijska analiza, rasprava o društvenim aspektima statističkih rezultata, aktivno sudjelovanje u raspravi na zadanu temu.














