---
title: " "
---

<br>
<br>

## Predavanje 01: Pregled kolegija i studentskih obveza

- Uvod u kolegij
- Potrebe, interesi i ciljevi
- Rasprava: Zašto (podatkovna) znanost?
- Software 
    
    
## Predavanje 02: Uvod u R


- Radni prostor
- Osnovne naredbe
- Funkcije
- Vektori
- Logički operatori


<b>Format predavanja:</b> <a href="https://github.com/BrbanMiro/WebStatistika/blob/main/Moduli/01_UVOD.Rmd">.html</a> | <a href="https://github.com/BrbanMiro/WebStatistika/blob/main/Moduli/01_UVOD.pdf">.pdf</a> | <a href="https://github.com/BrbanMiro/WebStatistika/blob/main/Moduli/02_UVOD_U_R.Rmd">.Rmd</a> (+ Dodatni koncepti R: <a href="https://github.com/BrbanMiro/WebStatistika/blob/main/Moduli/02_DODATNI_KONCEPTI_R.html">.html</a> | <a href="https://github.com/BrbanMiro/WebStatistika/blob/main/Moduli/02_DODATNI_KONCEPTI_R.pdf">.pdf</a> | <a href="https://github.com/BrbanMiro/WebStatistika/blob/main/Moduli/02_DODATNI_KONCEPTI_R.Rmd">.Rmd</a>)
<br><b>Čitanje: </b><a href="https://www.srce.unizg.hr/files/srce/docs/edu/R/s720_polaznik.pdf">Uvod u R - skripta I</a> + </b><a href="https://cran.r-project.org/doc/contrib/Kasum+Legovic-UvodUr.pdf">Uvod u R - skripta II</a> + </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR, poglavlja 3 i 4</a>



## Predavanje 03: Deskriptivna statistika



- Podatci
- Mjere centralne tendencije
- Mjere varijabilnosti
- Mjere asimetrije i zaobljenosti
- Pregled varijabli i skupova podataka
- Standardizirane vrijednostii
- Korelacija


<b>Format predavanja:</b>  <a href="/Moduli/03_DESKRIPTIVNA_STATISTIKA_xar.html">.html</a> | <a href="/Moduli/03_DESKRIPTIVNA_STATISTIKA_xar.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 5.</a>


## Predavanje 04: Vizualizacija podataka


- Vizualizacija, alati i podrška 
- Izrada jednostavnog grafikona
- Histogram
- Box-plot
- Prikaz korelacije
- Dijagram rasipanja
- Stupčasti grafikon

<b>Format predavanja:</b> <a href="/Moduli/04_GRAFIKONI_I_VIZUALIZACIJE_xar.html">.html</a> | <a href="/Moduli/04_GRAFIKONI_I_VIZUALIZACIJE_xar.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 6.</a>


## Predavanje 05: Distribucije


- Deskriptivna vs. inferencijalna statistika
- Binomna distribucija
- Standardna distribucija
- Druge često korištene distribucije


<b>Format predavanja:</b> <a href="/Moduli/05_VJEROJATNOST.html">.html</a> | <a href="/Moduli/05_VJEROJATNOST..Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 9.</a>


## Predavanje 06: Uzorak i populacija

- Uzorak i populacija
- Procjena prosjeka i standardne devijacije populacije
- Sampling distribucije
- Teorem centralne tendencije
- Intervali pouzdanosti

<b>Format predavanja:</b> <a href="/Moduli/06_UZORAK_POPULACIJA.html">.html</a> | <a href="/Moduli/06_UZORAK_POPULACIJA.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 10.</a>


## Predavanje 07: Testiranje hipoteza


- Vrste pogrešaka
- Testna statistika i sampling distribucija
- Kritičke vrijednosti i granice
- p-vrijednosti
- Interpretacija rezultata
- Testiranje hipoteza u R
- Efekt veličine i snaga testa
- Dodatni koncepti

<b>Format predavanja:</b> <a href="/Moduli/07_HIPOTEZE.html">.html</a> | <a href="/Moduli/07_HIPOTEZE.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 11.</a>


## Predavanje 08: Kategorijalna analiza


- Goodness-of-fit test
- Test nezavisnosti
- Korekcija kontinuiranosti
- Efekt veličine
- Pretpostavke testa
- Izvođenje chi-sq testova u R
- Fisherov test za male uzorke
- McNemarov test zavisnih uzoraka


<b>Format predavanja:</b> <a href="/Moduli/08_KATEGORIJALNA_ANALIZA.html">.html</a> | <a href="/Moduli/08_KATEGORIJALNA_ANALIZA.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 12.</a>


## Predavanje 09: Usporedba prosjeka


- z-test
- t-test
- t-test u nezavisnim uzorcima
- t-test u zavisnim uzorcima
- Jednostrani testovi
- Izvođenje t-testova u R
- Efekt veličine
- Provjera normalnosti distribucije



<b>Format predavanja:</b> <a href="/Moduli/09_USPOREDBA_PROSJEKA.html">.html</a> | <a href="/Moduli/09_USPOREDBA_PROSJEKA.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 13.</a>


## Predavanje 10: ANOVA


- ANOVA
- ANOVA u R
- Efekt veličine
- Post hoc testovi
- Pretpostavke jednostrane ANOVA-e
- Homogenost varijance
- Normalnost distribucije



<b>Format predavanja:</b> <a href="/Moduli/10_ANOVA.html">.html</a> | <a href="/Moduli/10_ANOVA.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 14.</a>


## Predavanje 11: Linearna regresija


- Linearna regresija
- Multivarijatna linearna regresija
- Karakteristike procijenjenog modela
- Testiranje hipoteza
- Pretpostavke modela
- Provjera modela
- Izbor parametara modela

<b>Format predavanja:</b> <a href="/Moduli/11_REG.html">.html</a> | <a href="/Moduli/11_REG.Rmd">.Rmd</a>
<br><b>Čitanje: </b><a href="https://learningstatisticswithr.com/lsr-0.6.pdf">LSR,poglavlje 15.</a>


## Predavanje 12: Faktorska ANOVA


- Faktorska ANOVA (balansirani dizajn;bez interakcija)
- Faktorska ANOVA (balansirani dizajn;interakcije)
- Efekt veličine
- Provjera pretpostavki
- Faktorska ANOVA (nebalansirani dizajn)

<br>
<br>
<br>


