---
title: "PRIMJENJENA STATISTIKA"
# subtitle: "<html><div style='float:left'></div><hr color='#EB811B' size=1px width=796px></html>"
subtitle: "Predavanje 1: Pregled kolegija"
author: "Luka Sikic, PhD"
date: "Fakultet hrvatskih studija | [Github PS](https://github.com/BrbanMiro/WebStatistika)" #"`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


class: inverse, middle

```{R, setup, include = F}
# devtools::install_github("dill/emoGG")
library(pacman)
p_load(
  broom, tidyverse,
  latex2exp, ggplot2, ggthemes, ggforce, viridis, extrafont, gridExtra,
  kableExtra, snakecase, janitor,
  data.table, dplyr, estimatr,
  lubridate, knitr, parallel,
  lfe,
  here, magrittr
)
# Define pink color
red_pink <- "#e64173"
turquoise <- "#20B2AA"
orange <- "#FFA500"
red <- "#fb6107"
blue <- "#2b59c3"
green <- "#8bb174"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
purple <- "#6A5ACD"
slate <- "#314f4f"
# Dark slate grey: #314f4f
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F
)
opts_chunk$set(dev = "svg")
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
options(crayon.enabled = F)
options(knitr.table.format = "html")
# A blank theme for ggplot
theme_empty <- theme_bw() + theme(
  line = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  plot.margin = structure(c(0, 0, -0.5, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_simple <- theme_bw() + theme(
  line = element_blank(),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text.x = element_text(size = 18, family = "STIXGeneral"),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  # plot.margin = structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_math <- theme_void() + theme(
  text = element_text(family = "MathJax_Math"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_serif <- theme_void() + theme(
  text = element_text(family = "MathJax_Main"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes <- theme_void() + theme(
  text = element_text(family = "Fira Sans Book"),
  axis.title = element_text(size = 18),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 20))
# Column names for regression results
reg_columns <- c("Term", "Est.", "S.E.", "t stat.", "p-Value")
# Function for formatting p values
format_pvi <- function(pv) {
  return(ifelse(
    pv < 0.0001,
    "<0.0001",
    round(pv, 4) %>% format(scientific = F)
  ))
}
format_pv <- function(pvs) lapply(X = pvs, FUN = format_pvi) %>% unlist()
# Tidy regression results table
tidy_table <- function(x, terms, highlight_row = 1, highlight_color = "black", highlight_bold = T, digits = c(NA, 3, 3, 2, 5), title = NULL) {
  x %>%
    tidy() %>%
    select(1:5) %>%
    mutate(
      term = terms,
      p.value = p.value %>% format_pv()
    ) %>%
    kable(
      col.names = reg_columns,
      escape = F,
      digits = digits,
      caption = title
    ) %>%
    kable_styling(font_size = 20) %>%
    row_spec(1:nrow(tidy(x)), background = "white") %>%
    row_spec(highlight_row, bold = highlight_bold, color = highlight_color)
}
```

```{css, echo = F, eval = F}
@media print {
  .has-continuation {
    display: block !important;
  }
}
```

## TEHNIČKI DETALJI


---
layout: true
# TEHNIČKI DETALJI
---
<br>
<br>
<br>
- Nastava iz obveznog kolegija **Primjena statistike u društvenim istraživanjima** sastoji se od dva sata predavanja i dva sata seminara tjedno (7 ECTS). 
- Predavanja se održavaju u blok satima (dva školska sata od 45 min) kao i seminar.
- Pohađanje nastave (i predavanja i seminara) je obavezno i evidentira se. 
- Predavanje se održava ponedjeljkom od 16:00 do 17:30 u a seminar odmah iza predavanja od 17:30 do 19:00 u dvorani xy. 
- Tijekom nastave, molim studente da ne koriste mobitele i ne izlaze iz dvorane.


---
layout: false
class: middle, inverse

# CILJEVI KOLEGIJA
---
layout: true
# CILJEVI KOLEGIJA
---
<br>
<br>
<br>
- Upoznati vas sa osnovama programskog sučelja [**R**](https://rstudio.com/).
- Osposobiti vas za primjenu osnovnih statističkih koncepata u programu **R**. 
- Naučiti vas kako operacionalizirati osnovne statističke koncepte u empirijskoj analizi i interpretirati rezultate. 
- Upoznati vas sa važnostima, korisnostima i znanstvenom relevantnosti domaćih i stranih sekundarnih izvora podataka (npr. Iz [**DZS**](https://www.dzs.hr/), [**HGK**](https://www.hgk.hr/), [**EUROSTAT**](https://ec.europa.eu/eurostat/data/database) i sl.).


---
layout: false
class: middle, inverse

# SADRŽAJ KOLEGIJA
---
layout: true
# SADRŽAJ KOLEGIJA
---
<br>
<br>
<br>

- Računalna podrška: **R** osnove, dodatni koncepti u **R**.
- Pregled podataka: deskriptivna statistika, vizualizacija podataka.
- Statistička teorija: vjerojatnost, distribucije, procjena parametara, testiranje hipoteza.
- Statistički alati: kategorijalna analiza, usporedba dva prosjeka, usporedba više prosjeka, osnove regresijske analize.


---
layout: false
class: middle, inverse

# STUDENTSKE OBVEZE
---
layout: true
# STUDENTSKE OBVEZE (Predavanja)
---
<br>
<br>
<br>

- Studentima se preporučuje da na predavanjima koriste svoje prijenosno računalo i zapisuju bilješke.
- Predavanja će biti dostupna nakon svakog predavanja.
- Predavanja su sastavni dio ispita.
- Nije dopušteno snimanje predavanja.

---
layout: true
# STUDENTSKE OBVEZE (Prezentacija)
---
<br>
<br>
<br>

- Svi studenti tijekom semestra moraju održati jednu prezentaciju prema zadanoj literaturi u .ppt formi.   
- Izlagači  moraju pripremiti na kraju prezentacije i nekoliko (2-3) ključnih pitanja za raspravu koju imamo na kraju obrađene teme.
- Prezentaciju studenti moraju poslati profesoru na e-mail najkasnije u petak, tjedan dana prije seminara. 
- Seminari osim prezentacije uključuju: povezivanje teorijskih koncepata s praktičnom primjenom, zajednička empirijska analiza, rasprava o društvenim aspektima statističkih rezultata, aktivno sudjelovanje u raspravi na zadanu temu.

---
layout: true
# STUDENTSKE OBVEZE (Kolokvij i Ispit)
---
<br>
<br>
<br>

- Studentima se preporuča i omogućuje da polože kolegij kroz prezentaciju i dva kolokvija. Sustav bodovanja za studente koji polažu kolegij preko kolokvija: moguće je skupiti 100 bodova, pri tome je na prezentaciji moguće ostvariti do 10 bodova, a na svakom kolokviju do 40 bodova. Pri tome je sustav bodovanja jednak kao kod ispita(vidi niže!).
- U zimskom , ljetnom   i jesenskom  ispitnom roku studenti imaju završni pismeni ispit iz tema obrađenih na predavanjima i prema priloženoj literaturi. 
- Ispit je položen ako student ostvari 60% od ukupno mogućih bodova: 60-64% = (2); 65-74% = (3); 75-84% = (4); 85% = (5)

---
layout: false
class: middle, inverse

# LITERATURA
---

layout: true
# LITERATURA
---
<br>
<br>
<br>

- [**Materijali**](https://github.com/BrbanMiro/WebStatistika) koji će biti distribuirani u toku kolegija
- [**Navarro, D. (2014)** *Learning statistics with R: A tutorial*](https://learningstatisticswithr.com/)
- **Petz, B. (1997).** *Osnovne statističke metode za nematematičare*, III, Naklada  Slap, Jastrebarsko

---
layout: false
class: middle, inverse

# KONZULTACIJE
---

layout: true
# KONZULTACIJE
---
<br>
<br>
<br>

- od 15:00 do 16:00 u sobi 18 (prizemlje)
- prema dogovoru na mail: luka.sikic@hrstud.hr



---

layout:false
class: middle, inverse
# HVALA NA PAŽNJI! 
<html><div style='float:left'></div><hr color='#EB811B' size=1px width=796px></html>
(Sljedeće predavanje: Uvod u R!)
